theme = "molokai"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"] # Is this necessary?
rulers = [80, 120]
bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

